import type {
  BackendBlueprintResponse, BackendEvaluationCriterion, BackendGroundedCommercialFinancialRule,
  BackendGroundedContractualRule, BackendGroundedQualificationRequirement, BackendGroundedTechnicalRequirement,
  BackendNormalizedRequirement, BackendSourceReference, BackendTenderRequirement,
} from "@/lib/tender-blueprint-contract";
import type { BlueprintPreview, BlueprintRequirement, ContractualGroup, FormulaDefinition, TechnicalCriterion } from "./types";

export class BlueprintMappingError extends Error {}

export function mapBackendBlueprint(response: BackendBlueprintResponse): BlueprintPreview {
  const source=response.blueprint;
  if(!source.source_filename||!Array.isArray(source.requirements)||!Array.isArray(source.evaluation_stages))throw new BlueprintMappingError("The Blueprint response is incomplete");
  const baseline=source.requirements.map(mapRequirement); const semantics=response.grounded_semantics;
  const technicalStages=source.evaluation_stages.filter(stage=>stage.stage_type.toUpperCase().includes("TECH"));
  const baselineCriteria=technicalStages.flatMap(stage=>stage.criteria.map(mapCriterion));
  const semanticTechnical=semantics?.technical_requirements??[];
  const technicalCriteria=semantics?semanticTechnical.filter(item=>item.kind==="SCORED_CRITERION").map(mapTechnicalCriterion):baselineCriteria;
  const technicalRequirements=[...baseline.filter(item=>item.category==="technical"),...(semantics?semanticTechnical.filter(item=>item.kind==="TECHNICAL_REQUIREMENT").map(mapTechnicalRequirement):[])];
  const qualification=[...baseline.filter(item=>item.category==="qualification"),...(semantics?.qualification_requirements.map(mapQualificationRequirement)??[])];
  const semanticCommercial=semantics?.commercial_financial_rules??[];
  const commercialRules=[...baseline.filter(item=>item.category==="commercial"),...semanticCommercial.filter(item=>item.kind==="COMMERCIAL_RULE"||item.kind==="FINANCIAL_REQUIREMENT").map(mapCommercialRule)];
  const baselineContractual=baseline.filter(item=>item.category==="contractual");
  const contractual=semantics?groupContractual(baselineContractual,semantics.contractual_rules):baselineContractual.length?[{label:"Contractual requirements",rules:baselineContractual}]:[];
  const allRequirements=[...qualification,...technicalCriteria,...technicalRequirements,...commercialRules,...contractual.flatMap(group=>group.rules)];
  const allSources=allRequirements.flatMap(item=>[{page:item.evidence.page},...(item.evidence.additionalSources??[])]);
  const semanticThreshold=semanticTechnical.find(item=>item.kind==="OVERALL_THRESHOLD")?.threshold_value;
  const threshold=semanticThreshold??technicalStages.map(stage=>stage.minimum_score).find(value=>value!==null)??0;
  const total=technicalCriteria.reduce((sum,item)=>sum+(item.maximumMarks??0),0);
  const formulaStages=source.evaluation_stages.filter(stage=>stage.formula);
  const baselineFinancial=formulaStages.find(stage=>/financial/i.test(`${stage.name} ${stage.stage_type}`)&&!/consolidated|combined|qcbs/i.test(`${stage.name} ${stage.stage_type}`));
  const baselineCombined=formulaStages.find(stage=>/consolidated|combined|qcbs/i.test(`${stage.name} ${stage.stage_type}`));
  const semanticFinancial=semanticCommercial.find(item=>item.kind==="FINANCIAL_SCORE_FORMULA");
  const semanticCombined=semanticCommercial.find(item=>item.kind==="WEIGHTED_SCORE_FORMULA");
  return {dataSource:"backend",tender:{title:source.metadata.title??"Untitled tender",reference:source.metadata.reference_number??"Reference not provided",document:source.source_filename,pages:allSources.reduce((maximum,item)=>Math.max(maximum,item.page),0),status:allRequirements.some(item=>item.review==="needs-review")?"Review Required":"Blueprint Generated"},qualification,technical:{threshold,total,criteria:technicalCriteria,requirements:technicalRequirements},commercial:{financialFormula:semanticFinancial?.formula_expression?mapSemanticFormula(semanticFinancial):baselineFinancial?.formula?mapFormula(baselineFinancial.name,baselineFinancial.formula,baselineFinancial.weight_percent):undefined,combinedFormula:semanticCombined?.formula_expression?mapSemanticFormula(semanticCombined):baselineCombined?.formula?mapFormula(baselineCombined.name,baselineCombined.formula,baselineCombined.weight_percent):undefined,rules:commercialRules},contractual};
}

function mapRequirement(item:BackendTenderRequirement):BlueprintRequirement{return {...grounded(item.requirement_id,item.source_references,item.normalized_text||item.raw_text,item.requires_review),category:mapCategory(item.category),title:item.normalized_text||item.raw_text,description:item.raw_text,mandatory:item.mandatory,value:formatNormalizedValue(item.normalized),evidenceExpected:item.expected_evidence.length?item.expected_evidence:undefined,review:item.requires_review||item.mandatory===null?"needs-review":"ready",reviewReason:item.requires_review?"A detailed review reason was not supplied by the Blueprint service.":undefined}}
function mapQualificationRequirement(item:BackendGroundedQualificationRequirement):BlueprintRequirement{return {...grounded(item.requirement_id,item.source_references,item.requirement_text,item.requires_review),category:"qualification",title:item.title,description:item.requirement_text,mandatory:item.mandatory,value:formatNormalizedValue(item.normalized),reviewReason:item.review_reason??undefined}}
function mapCriterion(item:BackendEvaluationCriterion):TechnicalCriterion{return {...grounded(item.criterion_id,item.source_references,item.raw_rule,item.requires_review),category:"technical",title:item.name,description:item.raw_rule,mandatory:true,maximumMarks:item.maximum_score,minimumMarks:item.minimum_score,value:item.weight_percent===null?undefined:`${item.weight_percent}% weight`,reviewReason:item.requires_review?"A detailed review reason was not supplied by the Blueprint service.":undefined}}
function mapTechnicalCriterion(item:BackendGroundedTechnicalRequirement):TechnicalCriterion{return {...grounded(item.requirement_id,item.source_references,item.description,item.requires_review),category:"technical",title:item.title,description:item.description,mandatory:item.mandatory,maximumMarks:item.maximum_marks,minimumMarks:item.minimum_qualifying_marks,value:item.weight_percent===null?undefined:`${item.weight_percent}% weight`,evidenceExpected:item.expected_evidence.length?item.expected_evidence:undefined,reviewReason:item.review_reason??undefined}}
function mapTechnicalRequirement(item:BackendGroundedTechnicalRequirement):BlueprintRequirement{return {...grounded(item.requirement_id,item.source_references,item.description,item.requires_review),category:"technical",title:item.title,description:item.description,mandatory:item.mandatory,evidenceExpected:item.expected_evidence.length?item.expected_evidence:undefined,reviewReason:item.review_reason??undefined}}
function mapCommercialRule(item:BackendGroundedCommercialFinancialRule):BlueprintRequirement{const value=item.money_value!==null?`${item.operator?`${item.operator} `:""}${item.currency?`${item.currency} `:""}${item.money_value}`:item.percentage_value!==null?`${item.operator?`${item.operator} `:""}${item.percentage_value}%`:undefined;return {...grounded(item.rule_id,item.source_references,item.description,item.requires_review),category:"commercial",title:item.title,description:item.description,mandatory:item.mandatory,value,evidenceExpected:item.expected_evidence.length?item.expected_evidence:undefined,reviewReason:item.review_reason??undefined}}
function mapContractualRule(item:BackendGroundedContractualRule):BlueprintRequirement{const attributes=[item.responsible_party?{label:"Responsible party",value:humanize(item.responsible_party)}:null,item.obligation_semantics?{label:"Semantics",value:humanize(item.obligation_semantics)}:null,item.beneficiary_or_counterparty?{label:"Counterparty",value:humanize(item.beneficiary_or_counterparty)}:null].filter((entry):entry is {label:string;value:string}=>entry!==null);return {...grounded(item.rule_id,item.source_references,item.description,item.requires_review),category:"contractual",title:item.title,description:item.description,mandatory:item.mandatory,value:contractualValue(item),evidenceExpected:item.expected_evidence.length?item.expected_evidence:undefined,reviewReason:item.review_reason??undefined,attributes:attributes.length?attributes:undefined}}

function grounded(id:string,sources:BackendSourceReference[],interpretation:string,requiresReview:boolean){const evidence=firstSource(sources);return {id,review:requiresReview?"needs-review" as const:"ready" as const,evidence:{page:evidence.page_number,section:evidence.section,excerpt:evidence.excerpt,interpretation,sourceReference:evidence.clause??undefined,additionalSources:mapAdditionalSources(sources)}}}
function groupContractual(baseline:BlueprintRequirement[],items:BackendGroundedContractualRule[]):ContractualGroup[]{const groups=new Map<string,BlueprintRequirement[]>();if(baseline.length)groups.set("Contractual requirements",baseline);for(const item of items){const label=contractualGroup(item.kind);groups.set(label,[...(groups.get(label)??[]),mapContractualRule(item)])}return [...groups].map(([label,rules])=>({label,rules}))}
function contractualGroup(kind:string):string{if(kind==="DELIVERY_REQUIREMENT"||kind==="CONTRACTUAL_OBLIGATION")return "Contract & Delivery";if(kind==="SERVICE_LEVEL"||kind==="TRANSITION_SUPPORT")return "Service / Support";if(kind==="LIABILITY_INDEMNITY")return "Penalties & Liability";if(["LEGAL_COMPLIANCE","CONFIDENTIALITY_DATA_PROTECTION","INTELLECTUAL_PROPERTY","TERMINATION_REMEDY"].includes(kind))return "Legal & Governance";if(kind==="DISPUTE_GOVERNANCE")return "Dispute / Grievance";return "Contractual requirements"}
function contractualValue(item:BackendGroundedContractualRule):string|undefined{if(item.duration_value!==null&&item.duration_unit)return `${item.duration_value} ${humanize(item.duration_unit).toLowerCase()}${item.duration_value===1?"":"s"}`;if(item.percentage_value!==null)return `${item.operator?`${item.operator} `:""}${item.percentage_value}%`;if(item.money_value!==null)return `${item.operator?`${item.operator} `:""}${item.currency?`${item.currency} `:""}${item.money_value}`;if(item.numeric_value!==null)return `${item.operator?`${item.operator} `:""}${item.numeric_value}`;return item.deadline_or_timing??undefined}
function mapSemanticFormula(item:BackendGroundedCommercialFinancialRule):FormulaDefinition{const parts:Array<{label:string;value:string}>=[];if(item.formula_multiplier!==null)parts.push({label:"Multiplier",value:String(item.formula_multiplier)});if(item.technical_weight_percent!==null)parts.push({label:"Technical weight",value:`${item.technical_weight_percent}%`});if(item.financial_weight_percent!==null)parts.push({label:"Financial weight",value:`${item.financial_weight_percent}%`});for(const variable of item.formula_variables)parts.push({label:"Variable",value:humanize(variable)});return {label:item.title,expression:item.formula_expression!,parts}}
function mapAdditionalSources(sources:BackendSourceReference[]):NonNullable<BlueprintRequirement["evidence"]["additionalSources"]>|undefined{const additional=sources.slice(1).map(source=>({page:source.page_number,section:source.section,excerpt:source.excerpt,sourceReference:source.clause??undefined}));return additional.length?additional:undefined}
function firstSource(sources:BackendSourceReference[]):BackendSourceReference{const source=sources[0];if(!source)throw new BlueprintMappingError("A Blueprint item is missing its required source evidence");return source}
function mapCategory(category:BackendTenderRequirement["category"]):BlueprintRequirement["category"]{if(category==="TECHNICAL")return "technical";if(category==="FINANCIAL"||category==="COMMERCIAL")return "commercial";if(category==="CONTRACTUAL"||category==="OTHER")return "contractual";return "qualification"}
function formatNormalizedValue(item:BackendNormalizedRequirement):string|undefined{if(item.value===null)return undefined;const prefix=item.operator?`${item.operator} `:"";const currency=item.currency?`${item.currency} `:"";const suffix=[item.unit,item.period].filter(Boolean).join(" · ");return `${prefix}${currency}${String(item.value)}${suffix?` ${suffix}`:""}`}
function mapFormula(label:string,expression:string,weight:number|null):FormulaDefinition{return {label,expression,parts:weight===null?[]:[{label:"Weight",value:`${weight}%`}]}}
function humanize(value:string):string{return value.toLowerCase().split("_").map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(" ")}
