import type { BlueprintPreview, BlueprintRequirement, EvidenceSource } from "./types";

const evidence = (page: number, section: string, excerpt: string, interpretation: string, id: string): EvidenceSource => ({
  page, section, excerpt, interpretation, evidenceId: id, sourceReference: `IT Software RPF.pdf · Page ${page}`,
});

const requirement = (item: BlueprintRequirement): BlueprintRequirement => item;

export const previewBlueprint: BlueprintPreview = {
  tender: { title: "IT Software RFP", reference: "IIITB/IT/RFP/2026", document: "IT Software RPF.pdf", pages: 68, status: "Blueprint Generated" },
  qualification: [
    requirement({ id:"QUAL-001",category:"qualification",title:"Minimum operational experience",description:"Bidder must have operated in the relevant technology domain for at least five years.",mandatory:true,value:"≥ 5 years",evidenceExpected:["Company registration","Work history"],review:"ready",evidence:evidence(20,"Eligibility Criteria","The bidder should have been in operation for at least five years.","Minimum operational history normalized to five years.","EVI-Q-001") }),
    requirement({ id:"QUAL-002",category:"qualification",title:"Profitability requirement",description:"Bidder must have recorded profits in at least two of the previous three financial years.",mandatory:true,value:"2 of 3 years",evidenceExpected:["Audited financial statements"],review:"ready",evidence:evidence(21,"Financial Eligibility","The bidder shall be profitable in at least two out of the last three financial years.","Profitability period and threshold preserved.","EVI-Q-002") }),
    requirement({ id:"QUAL-003",category:"qualification",title:"Average annual turnover",description:"Average annual turnover must meet the stated financial eligibility threshold.",mandatory:true,value:"₹40 crore",evidenceExpected:["Turnover certificate","Audited statements"],review:"ready",evidence:evidence(21,"Financial Eligibility","Average annual turnover during the last three years shall be INR 40 Crore.","Currency and crore magnitude normalized.","EVI-Q-003") }),
    requirement({ id:"QUAL-004",category:"qualification",title:"Blacklisting declaration",description:"Bidder must confirm that it is not blacklisted by any government or public authority.",mandatory:true,evidenceExpected:["Signed declaration"],review:"ready",evidence:evidence(22,"Declarations","The bidder shall not have been blacklisted by any Government department.","A mandatory negative declaration is required.","EVI-Q-004") }),
    requirement({ id:"QUAL-005",category:"qualification",title:"NASSCOM membership",description:"Valid NASSCOM membership must be demonstrated.",mandatory:true,evidenceExpected:["Membership certificate"],review:"needs-review",reviewReason:"The source references membership in a published schedule; confirm the required validity period.",evidence:evidence(22,"Professional Membership","Bidder should be a member of NASSCOM as detailed in the schedule.","Membership is required; the validity period needs acknowledgement.","EVI-Q-005") }),
    requirement({ id:"QUAL-006",category:"qualification",title:"ISO 9001 certification",description:"Bidder must hold a valid ISO 9001 quality-management certification.",mandatory:true,evidenceExpected:["ISO 9001 certificate"],review:"ready",evidence:evidence(22,"Certifications","Valid ISO 9001 certification shall be submitted with the bid.","Certification and submission requirement structured.","EVI-Q-006") }),
    requirement({ id:"QUAL-007",category:"qualification",title:"ISO 27001 certification",description:"Bidder must hold a valid ISO 27001 information-security certification.",mandatory:true,evidenceExpected:["ISO 27001 certificate"],review:"ready",evidence:evidence(22,"Certifications","Valid ISO 27001 certification shall be submitted with the bid.","Information-security certification requirement structured.","EVI-Q-007") }),
    requirement({ id:"QUAL-008",category:"qualification",title:"Data-security undertaking",description:"A signed undertaking covering prescribed data-security responsibilities is required.",mandatory:true,evidenceExpected:["Signed security undertaking"],review:"ready",evidence:evidence(23,"Security Undertaking","The bidder shall submit the data security undertaking in the prescribed format.","Required evidence and mandatory status preserved.","EVI-Q-008") }),
    requirement({ id:"QUAL-009",category:"qualification",title:"Local support presence",description:"Bidder must demonstrate support presence for on-site service requirements.",mandatory:true,evidenceExpected:["Office address","Support declaration"],review:"needs-review",reviewReason:"Confirm whether the support presence must exist at bid submission or may be established after award.",evidence:evidence(23,"Support Presence","The successful bidder shall maintain local support presence as specified.","Local support obligation identified; timing remains reviewable.","EVI-Q-009") }),
  ],
  technical: {
    threshold:65,total:100,
    criteria: [
      ["TECH-001","Relevant Experience",20,12,27],["TECH-002","Completeness of Proposed Solution",15,9,27],
      ["TECH-003","Support Methodology",20,12,27],["TECH-004","Presentation",10,6,28],
      ["TECH-005","Quality Assurance",15,9,28],["TECH-006","Staffing / Team",20,12,28],
    ].map(([id,title,maximumMarks,minimumMarks,page]) => ({ id:String(id),category:"technical" as const,title:String(title),description:`Scored technical criterion for ${String(title).toLowerCase()}.`,mandatory:true,maximumMarks:Number(maximumMarks),minimumMarks:Number(minimumMarks),review:"ready" as const,evidence:evidence(Number(page),"Technical Evaluation",`${String(title)} · Maximum ${maximumMarks} · Minimum qualifying ${minimumMarks}`,"Maximum and minimum scores reconstructed from the evaluation matrix.",`EVI-${id}`) })),
    requirements: [requirement({ id:"TECH-007",category:"technical",title:"Implementation approach",description:"Proposal must provide a practical implementation approach, governance model and delivery sequence.",mandatory:true,evidenceExpected:["Implementation plan"],review:"needs-review",reviewReason:"The required implementation phases span multiple tender sections and should be confirmed together.",evidence:evidence(16,"Scope and Implementation","The bidder shall provide a comprehensive implementation methodology and delivery plan.","Non-scored technical deliverable retained for review.","EVI-T-007") })],
  },
  commercial: {
    financialFormula:{ label:"Financial Score",expression:"(Lowest Valid Bid / Bidder Bid Value) × 100",parts:[{label:"Reference bid",value:"Lowest Valid Bid"},{label:"Evaluated bid",value:"Bidder Bid Value"},{label:"Multiplier",value:"100"}] },
    combinedFormula:{ label:"Consolidated Score",expression:"Technical Score × 0.70 + Financial Score × 0.30",parts:[{label:"Technical weight",value:"70%"},{label:"Financial weight",value:"30%"}] },
    rules:[
      requirement({id:"COM-001",category:"commercial",title:"Commercial bid format",description:"Commercial response must follow the prescribed bid format.",mandatory:true,evidenceExpected:["Completed commercial schedule"],review:"ready",evidence:evidence(24,"Commercial Evaluation","The commercial bid shall be submitted in the prescribed format.","Prescribed commercial schedule is mandatory.","EVI-C-001")}),
      requirement({id:"COM-002",category:"commercial",title:"Masked commercial bid",description:"Technical submission must not disclose commercial values.",mandatory:true,review:"ready",evidence:evidence(24,"Commercial Evaluation","Commercial prices shall not appear in the technical bid.","Commercial separation requirement preserved.","EVI-C-002")}),
      requirement({id:"COM-003",category:"commercial",title:"Earnest Money Deposit",description:"Applicable EMD evidence must be submitted with the proposal.",mandatory:true,value:"Amount requires confirmation",evidenceExpected:["EMD instrument"],review:"needs-review",reviewReason:"Two monetary values appear in the relevant schedule without an unambiguous label association.",evidence:evidence(11,"Bid Security","EMD / security amounts are provided in the published schedule.","The obligation is clear, but amount association needs confirmation.","EVI-C-003")}),
    ],
  },
  contractual: [
    {label:"Contract & Delivery",rules:[
      requirement({id:"CON-001",category:"contractual",title:"Contract signing",description:"Selected bidder must complete contract signing within the stated award window.",mandatory:true,value:"Within 30 days",review:"ready",evidence:evidence(31,"Award and Contract","The successful bidder shall sign the Contract within 30 days.","Contract execution deadline normalized.","EVI-O-001")}),
      requirement({id:"CON-002",category:"contractual",title:"Performance Bank Guarantee",description:"Selected bidder must provide the performance security after award.",mandatory:true,value:"Within 15 days",evidenceExpected:["Performance Bank Guarantee"],review:"ready",evidence:evidence(32,"Performance Security","Performance Bank Guarantee shall be submitted within 15 days.","Submission deadline and expected instrument preserved.","EVI-O-002")}),
      requirement({id:"CON-003",category:"contractual",title:"Contract duration and renewal",description:"Initial contract period is three years with yearly purchase-order renewals.",mandatory:false,value:"3 years · annual renewal",review:"ready",evidence:evidence(25,"Contract Period","The initial contract is expected to be signed for 3 years with purchase order renewals yearly.","Duration preserved without inventing a unilateral actor.","EVI-O-003")}),
    ]},
    {label:"Service / Support",rules:[requirement({id:"CON-004",category:"contractual",title:"Service reporting",description:"Service provider must maintain service-level reporting and verification records.",mandatory:true,evidenceExpected:["SLA reports"],review:"ready",evidence:evidence(16,"Service Levels","Bidder shall monitor and generate reports required for cross-verification of SLAs.","Ongoing reporting obligation structured.","EVI-O-004")})]},
    {label:"Payment",rules:[requirement({id:"CON-005",category:"contractual",title:"Payment timeline",description:"Payment becomes due after receipt and validation of the invoice.",mandatory:true,value:"60 days after invoice receipt",review:"ready",evidence:evidence(25,"Payment Terms","Payments will be made after 60 days from receipt of invoice after adjustments.","Relative payment period preserved.","EVI-O-005")})]},
    {label:"Penalties & Liability",rules:[
      requirement({id:"CON-006",category:"contractual",title:"Liquidated damages rate",description:"Delay attracts liquidated damages calculated weekly.",mandatory:true,value:"0.5% per week",review:"ready",evidence:evidence(36,"Liquidated Damages","Liquidated damages at 0.5% per week shall apply for delay.","Weekly penalty rate remains tied to delay.","EVI-O-006")}),
      requirement({id:"CON-007",category:"contractual",title:"Maximum liquidated damages",description:"Total liquidated damages are capped against contract value.",mandatory:true,value:"3% of contract value",review:"ready",evidence:evidence(36,"Liquidated Damages","The amount of liquidated damages shall not exceed 3% of Total Contract value.","Penalty cap preserved separately from weekly rate.","EVI-O-007")}),
      requirement({id:"CON-008",category:"contractual",title:"Bidder indemnification",description:"Bidder should indemnify the client for the stated direct claims and losses.",mandatory:false,review:"needs-review",reviewReason:"The source uses advisory “should” language; acknowledge the intended contractual force.",evidence:evidence(35,"Indemnity","The Bidder should indemnify IIITB against the listed claims and losses.","Advisory modality preserved rather than upgraded to mandatory.","EVI-O-008")}),
    ]},
    {label:"Legal & Governance",rules:[
      requirement({id:"CON-009",category:"contractual",title:"Contract language",description:"Contract and governing documentation are to be maintained in English.",mandatory:true,value:"English",review:"ready",evidence:evidence(40,"Contract Language","The Contract shall be written in English language.","Required contract language identified.","EVI-O-009")}),
      requirement({id:"CON-010",category:"contractual",title:"Governing law",description:"Contract is governed by applicable Indian law.",mandatory:true,value:"Indian laws",review:"ready",evidence:evidence(40,"Applicable Law","The Contract shall be interpreted in accordance with the laws of India.","Governing law recorded without additional interpretation.","EVI-O-010")}),
      requirement({id:"CON-011",category:"contractual",title:"Termination for default",description:"Client may terminate the contract following a material default.",mandatory:false,value:"Client right",review:"ready",evidence:evidence(37,"Termination","IIITB may terminate the Contract for default in the circumstances stated.","Client termination right preserved as permission, not obligation.","EVI-O-011")}),
    ]},
    {label:"Dispute / Grievance",rules:[
      requirement({id:"CON-012",category:"contractual",title:"Pre-award grievance",description:"Vendor may raise a grievance within the prescribed review window.",mandatory:false,value:"Within 3 days",review:"ready",evidence:evidence(29,"Grievance Process","The vendor may raise a grievance within 3 days of the decision.","Vendor permission and relative period preserved.","EVI-O-012")}),
      requirement({id:"CON-013",category:"contractual",title:"Stage-II appeal",description:"Vendor may appeal an adverse decision to the designated authority.",mandatory:false,value:"Within 3 days",review:"ready",evidence:evidence(30,"Appeal Process","The vendor may appeal to the Director within 3 days.","Appeal right remains separate from the deadline.","EVI-O-013")}),
    ]},
  ],
};

export const allPreviewRequirements = (blueprint: BlueprintPreview): BlueprintRequirement[] => [
  ...blueprint.qualification, ...blueprint.technical.criteria, ...blueprint.technical.requirements,
  ...blueprint.commercial.rules, ...blueprint.contractual.flatMap((group) => group.rules),
];
