"use client";
import { useState } from "react";
import Link from "next/link";
import { apexDocuments,bphuTender,vendors } from "@/data/demo-procurement";
import styles from "../procurement.module.css";
const tabs=["Overview","Documents","Participation","Performance","Activity"] as const;const apex=vendors[0];
export function VendorDetail(){const[tab,setTab]=useState<(typeof tabs)[number]>("Overview");return <div className={styles.page}><header className={styles.detailHeader}><div className={styles.detailTitle}><p className={styles.kicker}>Supplier profile</p><h1>{apex.name}</h1><div className={styles.detailMeta}><span>Registration · Active</span><span className={`${styles.status} ${styles.success}`}>{apex.documentStatus}</span><span>{apex.activeBids} active bids</span></div></div><Link className="button" href="/organization/evaluation/apex-infra">View BPHU Evaluation</Link></header><div className={styles.tabs} role="tablist">{tabs.map(x=><button className={styles.tab} role="tab" aria-selected={tab===x} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==="Overview"&&<Overview/>}{tab==="Documents"&&<Documents/>}{tab==="Participation"&&<Participation/>}{tab==="Performance"&&<Performance/>}{tab==="Activity"&&<Activity/>}</div>}
function Overview(){return <><section className={styles.profileTop}><div className={styles.contentPanel}><h2>Procurement Profile</h2><p className={styles.subtle}>Apex Infra participates in construction and civil works procurements. This profile contains frontend demonstration records only.</p></div><div className={styles.profileStats}><div><small>Active Bids</small><strong>03</strong></div><div><small>Previous Awards</small><strong>04</strong></div><div><small>Evidence State</small><strong>96%</strong></div></div></section><section className={styles.infoGrid}>{[["Registration Status","Active"],["Current Participation",bphuTender.shortTitle],["Document Verification",apex.documentStatus],["Supplier Performance","Strong record"]].map(([a,b])=><article className={styles.info} key={a}><small>{a}</small><strong>{b}</strong></article>)}</section></>}
function Documents(){return <section className={styles.panel}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Document</th><th>Identifier</th><th>Validity</th><th>Verification State</th><th>Last Checked</th></tr></thead><tbody>{apexDocuments.map(d=><tr key={d.document}><td className={styles.titleCell}><strong>{d.document}</strong></td><td className={styles.mono}>{d.identifier}</td><td>{d.validity}</td><td><span className={`${styles.status} ${styles.success}`}>{d.state}</span></td><td className={styles.mono}>{d.checked}</td></tr>)}</tbody></table></div></section>}
function Participation(){return <section className={styles.panel}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Tender</th><th>Bid</th><th>Stage</th><th>Outcome / Status</th></tr></thead><tbody><tr><td className={styles.titleCell}><strong>{bphuTender.shortTitle}</strong><span>{bphuTender.reference}</span></td><td>{apex.bid}</td><td>Evaluation</td><td><Link className={styles.action} href="/organization/evaluation/apex-infra">Shortlisted · View →</Link></td></tr><tr><td>IT Infrastructure Modernization</td><td>—</td><td>Receiving Bids</td><td>Proposal in preparation</td></tr><tr><td>District Medical Equipment Supply</td><td>₹73,90,000</td><td>Completed</td><td>Awarded</td></tr></tbody></table></div></section>}
function Performance(){return <section className={styles.infoGrid}>{[["Delivery","On schedule"],["Quality","Meets recorded requirements"],["Compliance","Strong"],["Responsiveness","Within agreed timelines"]].map(([a,b])=><article className={styles.info} key={a}><small>{a}</small><strong>{b}</strong></article>)}</section>}
function Activity(){return <section className={styles.contentPanel}><h2>Vendor Activity</h2><div className={styles.timeline}>{[["14 Sep","Proposal submitted · BPHU Building"],["13 Sep","Turnover Certificate updated"],["10 Sep","Clarification answered"],["04 Sep","Compliance evaluation completed"],["18 Aug","Previous award recorded"]].map(([a,b])=><div className={styles.timelineItem} key={b}><time>{a}</time><span>{b}</span></div>)}</div></section>}
