"use client";
import { useState } from "react";
import Link from "next/link";
import { bphuDocuments,bphuRequirements,bphuTender,blueprintRecords } from "@/data/demo-procurement";
import styles from "../procurement.module.css";
const tabs=["Overview","Requirements","Documents","Blueprint","Activity"] as const;
export function TenderDetail(){const[tab,setTab]=useState<(typeof tabs)[number]>("Overview");return <div className={styles.page}><header className={styles.detailHeader}><div className={styles.detailTitle}><p className={styles.kicker}>Tender workspace</p><h1>{bphuTender.title}</h1><div className={styles.detailMeta}><span>{bphuTender.reference}</span><span>{bphuTender.organization}</span><span>{bphuTender.location}</span><span className={styles.status}>{bphuTender.stage}</span></div></div><div className={styles.actions}><button className="button button--ghost" type="button">Manage</button><button className="button" type="button" onClick={()=>setTab("Blueprint")}>View Blueprint</button></div></header><div className={styles.tabs} role="tablist" aria-label="Tender workspace sections">{tabs.map(item=><button key={item} className={styles.tab} role="tab" aria-selected={tab===item} onClick={()=>setTab(item)}>{item}</button>)}</div>{tab==="Overview"&&<Overview />}{tab==="Requirements"&&<Requirements />}{tab==="Documents"&&<Documents />}{tab==="Blueprint"&&<Blueprint />}{tab==="Activity"&&<Activity />}<div className={styles.integration}>Continue the lifecycle: <Link className={styles.action} href="/organization/evaluation">View Bids &amp; Evaluation →</Link></div></div>}
function Overview(){const items=[["Tender Type",bphuTender.type],["Bid Process",bphuTender.bidProcess],["Estimated Cost",bphuTender.estimatedCost],["Completion Time",bphuTender.completion],["EMD",bphuTender.emd],["Tender Fee",bphuTender.fee],["Bid Validity",bphuTender.validity],["Performance Security",bphuTender.performanceSecurity],["Submission Deadline",bphuTender.submission],["Opening",bphuTender.opening]];return <section className={styles.infoGrid}>{items.map(([label,value])=><article className={styles.info} key={label}><small>{label}</small><strong>{value}</strong></article>)}</section>}
function Requirements(){return <section className={styles.contentPanel}><h2>Structured Requirements</h2><div className={styles.recordList}>{bphuRequirements.map(item=><article className={styles.record} key={item.id}><div className={styles.recordTop}><small>{item.category}</small><code>{item.id}</code></div><h3>{item.title}</h3><p><strong>{item.rule}</strong><br />{item.detail}</p></article>)}</div></section>}
function Documents(){return <section className={styles.contentPanel}><h2>Mandatory and Expected Documents</h2><div className={styles.documentGrid}>{bphuDocuments.map(item=><div className={styles.document} key={item}>{item}</div>)}</div></section>}
function Blueprint(){return <section className={styles.contentPanel}><h2>Structured Tender Blueprint</h2><div className={styles.blueprint}>{blueprintRecords.map(item=><article className={styles.blueprintRecord} key={item.id}><div className={styles.blueprintId}>{item.id}<span>{item.category}</span></div><div><strong>{item.title}</strong><span>Source · {item.source}</span></div><div><small>Rule</small><strong>{item.operator} {item.required}</strong><span>{item.period}</span></div><div><small>Expected evidence</small><strong>{item.evidence}</strong><span>Mandatory · {item.mandatory}</span></div></article>)}</div></section>}
function Activity(){return <section className={styles.contentPanel}><h2>Tender Activity</h2><div className={styles.timeline}><div className={styles.timelineItem}><time>12 Sep</time><span>Tender moved to evaluation</span></div><div className={styles.timelineItem}><time>19 Dec</time><span>Submission window closed</span></div><div className={styles.timelineItem}><time>04 Dec</time><span>Clarification published</span></div></div></section>}
