"use client";
import { useState, type FormEvent } from "react";
import type { AccountRole } from "@/lib/demo-auth";
import { PasswordField } from "./password-field";
import { RoleToggle } from "./role-toggle";
import styles from "./auth.module.css";

type Fields = { name: string; email: string; company: string; password: string; confirmPassword: string };
type Errors = Partial<Record<keyof Fields, string>>;
const initialFields: Fields = { name: "", email: "", company: "", password: "", confirmPassword: "" };

export function RegisterForm() {
  const [role, setRole] = useState<AccountRole>("organization"); const [fields, setFields] = useState(initialFields); const [errors, setErrors] = useState<Errors>({}); const [submitted, setSubmitted] = useState(false);
  const update = (field: keyof Fields, value: string) => { setFields((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: undefined })); setSubmitted(false); };
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const next: Errors = {}; if (!fields.name.trim()) next.name = "Enter your full name."; if (!/^\S+@\S+\.\S+$/.test(fields.email)) next.email = "Enter a valid work email."; if (!fields.company.trim()) next.company = role === "organization" ? "Enter your organization name." : "Enter your business or company name."; if (fields.password.length < 8) next.password = "Password must be at least 8 characters."; if (fields.confirmPassword !== fields.password) next.confirmPassword = "Passwords do not match."; setErrors(next); if (Object.keys(next).length) { setSubmitted(false); return; } setSubmitted(true); }
  return <div className={styles.card}><header className={styles.cardHeader}><p className={styles.micro}>Create workspace identity</p><h1>Get started.</h1><p>Set up the basic identity for your future TenderIQ workspace.</p></header><RoleToggle value={role} onChange={(nextRole) => { setRole(nextRole); setSubmitted(false); setErrors((current) => ({ ...current, company: undefined })); }} /><form className={styles.form} onSubmit={submit} noValidate>{submitted ? <div className={styles.success} role="status">Account registration will be connected when authentication services are enabled.</div> : null}<div className={styles.twoCol}><TextField id="full-name" label="Full name" value={fields.name} onChange={(value) => update("name", value)} error={errors.name} autoComplete="name" /><TextField id="work-email" label="Work email" value={fields.email} onChange={(value) => update("email", value)} error={errors.email} autoComplete="email" /></div><TextField id="company" label={role === "organization" ? "Organization name" : "Business / company name"} value={fields.company} onChange={(value) => update("company", value)} error={errors.company} autoComplete="organization" /><div className={styles.twoCol}><PasswordField id="new-password" label="Password" value={fields.password} onChange={(value) => update("password", value)} error={errors.password} hint="At least 8 characters" autoComplete="new-password" /><PasswordField id="confirm-password" label="Confirm password" value={fields.confirmPassword} onChange={(value) => update("confirmPassword", value)} error={errors.confirmPassword} autoComplete="new-password" /></div><button className={`button ${styles.submit}`} type="submit">Create Account <span aria-hidden="true">→</span></button><p className={styles.secondary}>{submitted ? <>Prototype only · <a href="/login">Use Demo Access</a></> : <>Already have an account? <a href="/login">Sign in</a></>}</p></form></div>;
}

function TextField({ id, label, value, onChange, error, autoComplete }: { id: string; label: string; value: string; onChange: (value: string) => void; error?: string; autoComplete: string }) { return <div className={styles.field}><label htmlFor={id}>{label}</label><input className={styles.input} id={id} value={value} onChange={(event) => onChange(event.target.value)} autoComplete={autoComplete} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} />{error ? <span className={styles.error} id={`${id}-error`}>{error}</span> : null}</div>; }
