import Link from "next/link";
import { activeTenders, attentionItems, evaluationAgents, overviewMetrics, pipelineStages, recentActivity } from "@/data/organization-overview";
import { Icon } from "../icons";
import styles from "../organization.module.css";

export function OrganizationOverview() {
  return <><header className={styles.pageHeader}><div><p className={styles.eyebrow}>Procurement command center</p><h1>Overview</h1><p>Monitor active tenders, vendor participation and evaluation activity from one workspace.</p></div><Link className={`button ${styles.primaryAction}`} href="/organization/tenders/new"><Icon name="plus" />Create Tender</Link></header><ProcurementSummary /><div className={styles.overviewGrid}><ActiveProcurement /><AttentionRequired /></div><div className={styles.secondaryGrid}><EvaluationActivity /><ProcurementPipeline /></div><RecentActivity /></>;
}

function PanelHeader({ title, meta, href }: { title: string; meta: string; href?: string }) { return <header className={styles.panelHeader}><h2>{title}</h2>{href ? <Link href={href}>{meta} →</Link> : <span>{meta}</span>}</header>; }
function ProcurementSummary() { return <section className={styles.summary} aria-label="Procurement summary">{overviewMetrics.map((item) => <article className={styles.metric} key={item.label}><div className={styles.metricTop}><span>{item.label}</span><i className={`${styles.statusNode} ${styles[item.tone]}`} /></div><strong>{item.value}</strong><p>{item.detail}</p></article>)}</section>; }
function ActiveProcurement() { return <section className={styles.panel}><PanelHeader title="Active Procurement" meta="View all tenders" href="/organization/tenders" /><div className={styles.tenderTable}><div className={styles.tenderHead}><span>Tender</span><span>Stage</span><span>Deadline</span><span>Proposals</span><span>Evaluation</span></div>{activeTenders.map((tender) => <article className={styles.tenderRow} key={tender.reference}><div className={styles.tenderTitle}><strong>{tender.title}</strong><span>{tender.location} · {tender.reference}</span></div><span className={`${styles.stage} ${tender.stage === "Award Pending" ? styles.award : ""}`}>{tender.stage}</span><span className={styles.deadline}>{tender.deadline}</span><span className={styles.proposalCount}><b>{tender.proposals}</b> received</span><span className={styles.ref}>{tender.evaluation}</span></article>)}</div></section>; }
function AttentionRequired() { return <section className={styles.panel}><PanelHeader title="Attention Required" meta="4 open actions" /><div className={styles.attentionList}>{attentionItems.map((item) => <article className={styles.attentionItem} key={item.title}><span className={styles.attentionCount}>{item.count}</span><div><strong>{item.title}</strong><p>{item.context}</p></div></article>)}</div></section>; }
function EvaluationActivity() { return <section className={styles.panel}><PanelHeader title="Evaluation Activity" meta="Demo processing state" /><div className={styles.evaluationBody}><div className={styles.evaluationTop}><div><strong>BPHU Building Tender</strong><span>PCO/BBSR/953/144</span></div><div className={styles.evaluationScore}><b>84 / 100</b><small>PROPOSALS PROCESSED</small></div></div><div className={styles.progress}><i style={{ width: "84%" }} /></div><div className={styles.agentRows}>{evaluationAgents.map((agent) => <div className={`${styles.agentRow} ${agent.status === "Processing" ? styles.processing : ""}`} key={agent.name}><span>{agent.name}</span><span><i style={{ width: `${agent.progress}%` }} /></span><b>{agent.status}</b></div>)}</div><div className={styles.evidenceScore}><span>Evidence Mapping</span><b>92%</b></div></div></section>; }
function ProcurementPipeline() { return <section className={styles.panel}><PanelHeader title="Procurement Pipeline" meta="Current portfolio" /><div className={styles.pipeline}><div className={styles.pipelineRail}>{pipelineStages.map((stage) => <div className={styles.pipelineStep} key={stage.label}><div className={styles.pipelineNode}><i /></div><strong>{stage.label}</strong><span>{stage.value}</span></div>)}</div></div></section>; }
function RecentActivity() { return <section className={styles.panel}><PanelHeader title="Recent Procurement Activity" meta="Presentation data" /><div className={styles.activityList}>{recentActivity.map((item) => <article className={styles.activityItem} key={`${item.time}-${item.event}`}><time>{item.time}</time><strong>{item.event}</strong><span>{item.context}</span></article>)}</div></section>; }
