import { ArrowIcon, Eyebrow } from "./shared";

export function Hero() {
  return <section className="hero section-grid" id="top"><div className="hero-glow" /><div className="container hero-layout"><div className="hero-copy"><Eyebrow>Intelligent procurement infrastructure</Eyebrow><h1>From tender documents<br />to <span>defensible decisions.</span></h1><p className="hero-lede">TenderIQ structures complex requirements, maps vendor evidence, and orchestrates explainable evaluation—inside one connected procurement system.</p><div className="hero-actions"><a className="button" href="/register">Get Started <ArrowIcon /></a><a className="button button--ghost" href="#platform">Explore Platform <span aria-hidden="true">↓</span></a></div><div className="hero-proof" aria-label="Platform principles"><span><i /> Evidence grounded</span><span><i /> Explainable by design</span><span><i /> End-to-end traceability</span></div></div><TenderIntelligenceVisual /></div></section>;
}

function TenderIntelligenceVisual() {
  return <div className="intelligence-visual" aria-label="TenderIQ evidence intelligence visualization"><div className="visual-chrome"><span><i /> INTELLIGENCE MAP</span><span>TIQ / 001</span></div><div className="map-grid" /><svg className="map-lines" viewBox="0 0 660 530" preserveAspectRatio="none" aria-hidden="true"><path d="M154 130 C230 130 220 244 302 244" /><path d="M508 129 C430 129 452 244 365 244" /><path d="M158 395 C238 395 226 290 304 290" /><path d="M507 395 C431 395 442 290 365 290" /><circle cx="233" cy="179" r="3" /><circle cx="438" cy="177" r="3" /><circle cx="237" cy="348" r="3" /></svg><div className="map-node node-requirement"><span className="node-label">Requirement</span><strong>Annual turnover</strong><b>≥ ₹27.27L</b><small>FIN / 04 · Mandatory</small></div><div className="map-node node-evidence"><span className="node-label">Evidence</span><strong>Turnover Certificate</strong><b>₹68.0L</b><small>PDF · Page 12</small></div><div className="blueprint-core"><div className="scan-line" /><span className="core-icon"><i /><i /><i /></span><small>Tender Blueprint</small><strong>Financial Eligibility</strong><div className="core-meta"><span>Source linked</span><span>Rule parsed</span></div></div><div className="map-node node-validation"><span className="node-label">Validation</span><strong><i /> Compliant</strong><small>Rule match confirmed</small></div><div className="agent-cluster"><span>Evaluation agents</span><div><i>T</i><i>F</i><i>C</i><b>3 active</b></div></div><div className="decision-strip"><span>Decision intelligence</span><strong>Evidence chain complete</strong><i>100%</i></div></div>;
}
